// SPDX-License-Identifier: Apache-2.0
// Copy into your project and adapt the patterns and extension policy as needed.
import { randomUUID } from 'node:crypto';
import { glob, rename, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const args = process.argv.slice(2);
const noext = args[0] === '--noext';
if (noext) args.shift();
const [output, ...patterns] = args;
if (!output || !patterns.length) {
  throw new Error(
    'Usage: node generate-index.mjs [--noext] <output> <patterns...>',
  );
}

const destination = path.resolve(output);
const exports = new Set();
for await (const file of glob(patterns)) {
  if (
    path.resolve(file) === destination ||
    !/\.(?:[cm]?[jt]s|tsx|jsx)$/.test(file) ||
    /\.(?:test|private)\./.test(file) ||
    /\.d\.[cm]?ts$/.test(file) ||
    !(await stat(file)).isFile()
  ) {
    continue;
  }
  let specifier = path.relative(path.dirname(destination), path.resolve(file));
  specifier = specifier.split(path.sep).join('/');
  if (!specifier.startsWith('./') && !specifier.startsWith('../')) {
    specifier = `./${specifier}`;
  }
  specifier = noext
    ? specifier.replace(/\.[^.]+$/, '')
    : specifier
        .replace(/\.mts$/, '.mjs')
        .replace(/\.cts$/, '.cjs')
        .replace(/\.(?:ts|tsx|jsx)$/, '.js');
  exports.add(specifier);
}

if (!exports.size) {
  throw new Error(
    'No source files matched; the existing output was left intact.',
  );
}
const code = [
  '// Generated by scripts/generate-index.mjs',
  ...[...exports]
    .sort()
    .map((file) => `export * from ${JSON.stringify(file)};`),
  '',
].join('\n');
const temporary = `${destination}.${randomUUID()}.tmp`;
try {
  await writeFile(temporary, code, { flag: 'wx' });
  await rename(temporary, destination);
} finally {
  await rm(temporary, { force: true });
}
